### PR TITLE
fix: wrong system path on Windows PowerShell

### LINKED ISSUE #8: `jython: command not found` on Windows-Powershell
On **Windows** runners, the `jython` command is recognised **only** when the job `shell` is set to `bash`, but **fails** when set to `cmd` or `pwsh`

### PR DESCRIPTION
**Pull request by ZZy979**
Fix #8

### CODE REVIEW

**Comment by LukeSavefrogs** [comment]
Oh... I just found the problem, you removed the initialization for the Bash in Windows

**Comment by ZZy979** [comment]
> The tests keep failing for Windows 2.0-2.1, while it used to work before (see how [this run](https://github.com/LukeSavefrogs/jython21-backport/actions/runs/7873216666/job/21480062290) actually works --don't mind the tests failing 😄)...
> 
> I can't seem to understand why now it doesn't work...

But tests for Windows 2.0/2.1 also failed in the [last run](https://github.com/LukeSavefrogs/setup-jython/actions/runs/6844731225/job/18608974751) before I submitted this PR (6 months ago). I'm not sure whether it was the same reason "Could not find or load main class org.python.util.jython".

> Oh... I just found the problem, you removed the initialization for the Bash in Windows
> 
> Maybe this causes some problems?

System path added by `pwsh` (e.g. `C:\Users\runneradmin\.local\bin`) should also be recognized by `bash`, see my [test workflow](https://github.com/ZZy979/learn-git/actions/runs/8986427717/job/24682497844). I think this shouldn't cause problems.

What's more, in the [test results](https://github.com/LukeSavefrogs/setup-jython/actions/runs/8987198481/job/24685455961) for this PR, nothing was printed for Windows PowerShell (although the "jython: command not found" error was fixed and the test even passed 🤔 ).

**Comment by LukeSavefrogs** [comment]
[Partially fixed](https://github.com/LukeSavefrogs/setup-jython/commit/43da51698a354de4963dc2d97506e183952d31df).

Now the only problem is that it fails because it doesn't find the `javaos` module, which is the same 

image


> What's more, in the [test results](https://github.com/LukeSavefrogs/setup-jython/actions/runs/8987198481/job/24685455961) for this PR, nothing was printed for Windows PowerShell (although the "jython: command not found" error was fixed and the test even passed 🤔 )

This is strange indeed...

**Comment by LukeSavefrogs** [comment]
> But tests for Windows 2.0/2.1 also failed in the [last run](https://github.com/LukeSavefrogs/setup-jython/actions/runs/6844731225/job/18608974751) before I submitted this PR (6 months ago). I'm not sure whether it was the same reason "Could not find or load main class org.python.util.jython".
> 
> >

This is only partially true, since as you can see from the action run i posted some messages before, the action used to work on Windows with Jython 2.1 using Bash (now it doesn't).

**Comment by ZZy979** [comment]
I've rewritten shell commands for `bash` and `pwsh` separately. Now all the tests have passed (for both shells), except for version 2.0/2.1. I still get the strange error "no module named javaos", but I can't reproduce it on my PC.

image

**Comment by LukeSavefrogs** [comment]
> I've rewritten shell commands for `bash` and `pwsh` separately. Now all the tests have passed (for both shells), except for version 2.0/2.1. I still get the strange error "no module named javaos", but I can't reproduce it on my PC.
> 
> image

I know, it's even more strange since it used to work onlòy on Windows and not on other runners (while running the action locally with `act` ubuntu worked).

**Comment by ZZy979** [comment]
Can you rerun [this workflow](https://github.com/LukeSavefrogs/jython21-backport/actions/runs/7873216666/job/21480062290) (still using setup-jython@v3) to see whether it still works at present?

**Comment by LukeSavefrogs** [comment]
The tests are not working now

**Comment by LukeSavefrogs** [comment]
@ZZy979 For now, can you please exclude `macos` runners from the tests?

They are making way too much noise and the issue is actually tracked by #12..

**Comment by LukeSavefrogs** [comment]
Perfect!
It seems like the only tests that are still failing are the ones for Jy2.1 and Jy2.0 on Windows runners...

Great work @ZZy979! 
If we manage to fix them too I'll merge the PR

**Comment by ZZy979** [comment]
> It seems like the only tests that are still failing are the ones for Jy2.1 and Jy2.0 on Windows runners...

The purpose of this PR is to make it work on PowerShell, and now it has been achieved. Perhaps the failing tests for 2.0 and 2.1 can be tracked by another issue.

**Comment by LukeSavefrogs** [comment]
> Perhaps the failing tests for 2.0 and 2.1 can be tracked by another issue.

You're actually right... I took my time to look back into what I did before and it seems like the last working test was in June 2023 right after 44e3e84.

image

So the latest working version as of now remains `v3` and while [some things happened](https://github.com/LukeSavefrogs/setup-jython/compare/v3...main) in the meantime, it would be a breaking change to publish `v4` removing support for Jython 2.0 and 2.1 on Windows. For example, I use it almost everyday in projects of mine like [**Jython Backport**](https://github.com/LukeSavefrogs/jython21-backport) and [**JyCLI**](https://github.com/LukeSavefrogs/jycli) (which in turn are both used at work) and `v4` would be incompatible.

I'll merge this request and then we (if you can contribute i'd be very grateful) can try to understand why it stopped working.

**Comment by LukeSavefrogs** [comment]
**PR finally merged** 🎉

Great job @ZZy979 and thank you again for taking the time to fix the problem!

**Pull request merged**
